config/routes.rb
Rails.application.routes.draw do

  resources :saledetails
  
  resources :saleheaders do
    member do
      get 'show_saledetails' => 'saleheaders#show_saledetails'       
    end
  end
  
  resources :einvoices
  
  resources :products
  get 'graficos/index'

  resources :graficos
  resources :outkardexes
  resources :inkardexes 

  resources :compras do
    collection { post :import }
    collection { get :imprimir_datos }   
    collection { get :imprimir_codbarras }
  end

  resources :rotacion_inventarios

  resources :kardexes
  resources :conteos do
    collection { post :import }
  end
  resources :personas

  resources :regions

  resources :venta

  resources :equipos

  resources :fabricantes

  resources :visita

  resources :planvisita 

  resources :puntoventa

  resources :ciudads do
    collection { post :import }
  end

  resources :departamentos do
    collection { post :import }
  end

  resources :pais do
    collection { post :import }
  end

  resources :canals

  resources :tipocanals

  devise_for :users
  
  scope "/admin" do
    resources :users do
    collection { post :import }
    end    
  end
  
  resources :roles

  resources :users 

  resources :inventarios do
    collection { post :import }
    collection { get :imprimir_datos }   
    collection { get :imprimir_codbarras }
  end

  resources :tiendas
  

  resources :articulos do
    get 'reporte'  => 'articulos#reporte' 
    collection { post :import }  
    collection { get :rotacion_inventarios } 
    
    member do
      get 'show_inkardexes' => 'articulos#show_inkardexes'       
    end
  end

  resources :modelos 

  resources :componentes

  resources :medidas

  resources :empresas

  authenticated :user do
  end 
  root to: "welcome#index"
 

  end

app/models/saleheader.rb
require 'rubygems'
require 'roo'
class Saleheader < ActiveRecord::Base
  belongs_to :user
  has_many   :saledetails, dependent: :destroy
  accepts_nested_attributes_for :saledetails, 
             allow_destroy: true 
  validates_presence_of :typeID, :num_id, :citizenship, :allname, :email, 
                        :expeditionDate

  def saleheader_typeID
     saleheader.try(:typeID)
  end 
  
  def saleheader_descripcion
     saleheader.try(:citizenship)
  end 

  def saleheader_citizenship=(citizenship)
    self.saleheader = Saleheader.find_by_citizenship(citizenship)  if citizenship.present?
  end    

  def saleheader_descripcion=(descripcion)
    self.saleheader = Saleheader.find_by_descripcion(descripcion)  if descripcion.present?
  end  
end

app/controllers/saleheaders_controller.rb
class SaleheadersController < ApplicationController
  before_action :set_saleheader, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource
  skip_authorize_resource 


  # GET /saleheaders
  # GET /saleheaders.json
  def index
    @saleheaders = Saleheader.all
  end

  # GET /saleheaders/1
  # GET /saleheaders/1.json
  def show
  end

  # GET /saleheaders/new
  def new
    @saleheader = Saleheader.new
    @saleheader.saledetails.build
  end  

  # GET /saleheaders/1/edit
  def edit
    @saleheader.saledetails.build
  end

  # POST /saleheaders
  # POST /saleheaders.json
  def show_saledetails
    @saleheader = Saleheader.find(params[:id])
  end 

  def create
    @saleheader = Saleheader.new(saleheader_params)

    respond_to do |format|
      if @saleheader.save
        format.html { redirect_to @saleheader, notice: 'Saleheader was successfully created.' }
        format.json { render :show, status: :created, location: @saleheader }
      else
        format.html { render :new }
        format.json { render json: @saleheader.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /saleheaders/1
  # PATCH/PUT /saleheaders/1.json
  def update
    respond_to do |format|
      if @saleheader.update(saleheader_params)
        format.html { redirect_to @saleheader, notice: 'Saleheader was successfully updated.' }
        format.json { render :show, status: :ok, location: @saleheader }
      else
        format.html { render :edit }
        format.json { render json: @saleheader.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /saleheaders/1
  # DELETE /saleheaders/1.json
  def destroy
    @saleheader.destroy
    respond_to do |format|
      format.html { redirect_to saleheaders_url, notice: 'Saleheader was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_saleheader
      @saleheader = Saleheader.find(params[:id])
      
    end
    def set_saledetail
      @saledetail = Saledetail.find(params[:id])
    end
    # Never trust parameters from the scary internet, only allow the white list through.
    def saleheader_params
      params.require(:saleheader).permit(:typeID, :citizenship, :allname, :email, :expeditionDate, :grossvalue, :tax, :netvalue, :state, :num_id, :invoice_num, saledetails_attributes: [:id, :articulo_id, :line, :value, :quantity, :total, :discount_percent, :user_id])
    end
end

app/helpers/saleheaders_helper.rb
module SaleheadersHelper
end

app/views/saleheaders/_form.html.erb
<%= form_for(@saleheader) do |f| %>
  <% if @saleheader.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@saleheader.errors.count, "error") %> prohibited this saleheader from being saved:</h2>

      <ul>
      <% @saleheader.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
    
   <div class="field">
    <%= f.label :Factura_Numero %>  <%= f.text_field  :invoice_num, :disabled=>true %>

    <%= f.label :Fecha_de_expedición%>  <%= f.date_select :expeditionDate %>
    <%= f.label :Estado%> <%= f.select(:state ,[['Elaborada','0'],['Aprobada','1'],['Pagada','2']]) %>
  </div>
  <div class="field">
    <%= f.label :Cliente_Tipo_Identificacion %>   
    <%= f.select(:typeID ,[['Tarjeta de identidad','1'],['Cédula de ciudadanía','2'],['Tarjeta de extranjería','3'],['Cédula de extranjería','4'],['NIT','5'],['Pasaporte','6'],['NUIP','7'],['Permiso especial de permanencia','8']]) %> 
    <%= f.label :Numero %>
    <%= f.text_field :num_id, type: "number"%>
    <%= f.label :Nacionalidad%>
    <%= f.select(:citizenship ,[['Colombia'],['Costa Rica'],['Brasil'],['Estados Unidos'],['Rusia'],['España'],['Ecuador'],['Francia']]) %>
  </div>
  <div class="field">
    <%= f.label :Nombre_y_apellidos_del_cliente %>
    <%= f.text_field :allname%>
    <%= f.label :email %>
    <%= f.email_field :email, autofocus: true%>
  </div>
  <div class="field">
    <%= f.label :Total_Valor_bruto %>
    <%= f.text_field :grossvalue, :disabled=>true %>
    <%= f.label :Valor_Impuesto%>
    <%= f.text_field :tax, :disabled=>true  %>
    <%= f.label :Valor_neto%>
    <%= f.text_field :netvalue, :disabled=>true %>
  </div>

<h2>Detalle</h2>
<table class="table table-bordered table-striped">
  <th>Num</th>
  <th>Articulo</th>
  <th>Valor Unidad</th>
  <th>Cantidad</th>
  <th>Total</th>
  <th>% Descuento</th> 
  <th>Borrar</th> 
  <th colspan="3"></th>
<thead>
  <tbody>
  <%= f.fields_for :saledetails do |saledetail| %>
  <tr>
    <div class="sale_details_fields">
      <td><div class="field">
        <%= saledetail.number_field :line%>
      </div></td>
      <td><div class="field">
        <%= saledetail.collection_select :articulo_id, Articulo.where(user_id: current_user.id).order(:nombre), :id, :name_with_desc, 
        include_blank: false %>    
      </div></td>
      <td><div class="field">
        <%= saledetail.number_field :value  %>
      </div></td>
      <td><div class="field">
        <%= saledetail.number_field :quantity%>
      </div></td>
      <td><div class="field">
        <%= saledetail.number_field :total%>
      </div></td>
      <td><div class="field">
         <%= saledetail.number_field :discountpercent, :class => 'text_field', :step => 0.1 %>
      </div></td>
      <td><div class="field">
        <%= saledetail.check_box :_destroy %>
      </div></td>  
    </div>  
  </tr>
  <% end %>
  </tbody>
</thead>  
</table>  
<div class="actions">
   <%= f.submit %>
</div> 
<% end %>

app/views/saleheaders/_saleheader.html.erb
<tbody>   
  <tr>
   <td><%= saleheader.saledetail.item %></td>
   <td><%= @saledetail.line %></td>
   <td><%= saledetail.value%></td>  
   <td><%= saledetail.total %></td>
   <td><%= saledetail.saleheader.nombre %></td> 
   <td><%= link_to 'Show', saledetail, class: "btn btn-default btn-sm" %></td>
   <td><%= link_to 'Edit', edit_saledetail_path(saledetail), class: "btn btn-default btn-sm" %></td>
   <td><%= button_to 'Delete', saledetail, class: "btn btn-danger btn-sm", method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>  
</tbody>

app/views/saleheaders/edit.html.erb
<h1>Modificación de la factura de Venta</h1>

<%= render 'form' %>

<%= link_to 'Show', @saleheader %> |
<%= link_to 'Back', saleheaders_path %>

app/views/saleheaders/index.html.erb
<p id="notice"><%= notice %></p>
    <%= link_to 'Ingresar Factura de Venta', new_saleheader_path,  class: "btn-primary btn-sm" %>

<h1>Listado Factura de Venta</h1>

<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Datos Factura </p> 
          Número
      </th> 
      <th>Fecha De Expedición  </th>
      <th>Estado</th>
      <th>Datos Cliente </p> 
          Tipo Identificacion
      </th>
      <th>Numero</th>
      <th>Nacionalidad</th>
      <th>Nombre completo</th>
      <th>email</th>
      <th>Totales </p> 
          Valor Bruto
      </th>
      <th>Impuesto</th>
       <th>Valor Neto</th>
    <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @saleheaders.each do |saleheader| %>
     <tr>
        <td><%= saleheader.invoice_num %></td>
        <td><%= saleheader.expeditionDate %></td>     
        <td><%= saleheader.state %></td>   
        <td><%= saleheader.typeID %></td>
        <td><%= saleheader.num_id  %></td>
        <td><%= saleheader.citizenship  %></td>
        <td><%= saleheader.allname %></td>
        <td><%= saleheader.email %></td>
        <td><%= saleheader.grossvalue %></td>
        <td><%= saleheader.tax%></td>
        <td><%= saleheader.netvalue %></td>
        
           
      <tr>      
        <td><%= link_to 'Modificar', edit_saleheader_path(saleheader), class: "btn btn-success btn-sm" , class: "btn btn-success btn-sm"   %></td>
        <td><%= link_to 'Detalle', show_saledetails_saleheader_path(saleheader) , class: "btn btn-success btn-sm" %></td> 
        <td><%= link_to 'Destroy', saleheader, method: :delete, data: { confirm: 'Are you sure?' } ,  class: "btn btn-danger btn-sm" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/saleheaders/new.html.erb
<h1>Nueva Factura de Venta</h1>

<%= render 'form' %>

<%= link_to 'Back', saleheaders_path %>

app/views/saleheaders/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Numero Factura:</strong>
  <%= @saleheader.invoice_num %>
</p>
<p>
  <strong>Fecha De Expedición:</strong>
  <%= @saleheader.expeditionDate %>
</p>
<p>
  <strong>Estado:</strong>
  <%= @saleheader.state %>
</p>
<p><strong> Estado DIAN:</strong>
<%= @saleheader.num %></p>

<p> DATOS DEL CLIENTE </p>
<p>
  <strong>Tipo y Nùmero de Identificación:</strong>
  <%= @saleheader.typeID %>
  <%= @saleheader.num_id%>
</p>
<p>
  <strong>Nacionalidad :</strong>
  <%= @saleheader.citizenship  %>
</p>
<p>
  <strong>Nombre completo Organizacion:</strong>
  <%= @saleheader.allname %>
</p>
<p>
  <strong>email:</strong>
  <%= @saleheader.email %>
</p>
<p>
  <strong>Valor Bruto:</strong>
  <%= @saleheader.grossvalue%>
</p>

<p>
  <strong>Impuesto:</strong>
  <%= @saleheader.tax %>
</p>
<p>
  <strong>Valor Neto:</strong>
  <%= @saleheader.netvalue %>
</p>

<%= link_to 'Edit', edit_saleheader_path(@saleheader) %> |
<%= link_to 'Back', saleheaders_path %>

app/views/saleheaders/show_saledetails.html.erb
<p id="notice"><%= notice %></p>
<h1>Información de la Factura de Venta</h1>
  <div class="container-fluid">
    <div class="row" style="background-color:lightcyan">
    	<div class="col-md-5">
        	 <p><strong> Numero Factura:</strong>
        	    <%= @saleheader.invoice_num   %>  
	            <strong>| Fecha expedicion:</strong>
	            <%= @saleheader.expeditionDate %>
	            <strong>| Estado</strong>
	            <%= @saleheader.state %></p>
	        <p>  DATOS DEL CLIENTE </p>
	        <p><strong> Tipo Identificacion:</strong>
	           <%= @saleheader.typeID %>
	           <strong> | Numero:</strong>
	           <%= @saleheader.num_id %>        
	           <strong> | Nacionalidad:</strong>
	           <%= @saleheader.citizenship %>
	        </p>   
	        <p><strong> Nombre:</strong>
	           <%= @saleheader.allname%>
	           <strong> | email:</strong>
	           <%= @saleheader.email %>
	        </p>	    
            <p> TOTALES FACTURA:  
		    <strong> Valor_bruto <%= @saleheader.grossvalue %> </strong>  
		    <strong> | Valor Impuesto <%= @saleheader.tax %> </strong>
		    <strong> | Valor neto <%= @saleheader.netvalue %>
	        </strong>
 		</div>
 	</div>



	<h1>Detalles</h1>
	 <table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Num</th>
      <th>Articulo</th>
      <th>Valor Unidad</th>
      <th>Cantidad</th>
      <th>Total</th>
      <th>% Descuento</th>
       
      <th colspan="3"></th>
     </tr>
  </thead>
    <ul>
    	
    <% if @saleheader.saledetails.any? %>
      
  
       <% @saleheader.saledetails.each do |saledetail| %>
      <td><%= saledetail.line %></td>
      <td><%= saledetail.value %></td>
      <td><%= saledetail.quantity%></td>
      <td><%= saledetail.total %></td>
      <td><%= saledetail.discount_percent %></td>
      <td><%= saledetail.discountpercent %></td>
      <td><%= saledetail.saleheader_id %></td>
     <td><%= saledetail.user_id %></td>
     <td><%= saledetail.articulo_id %></td>
      
        
    <tr>      
        
       
  
   </tr>
       <% end %>
    <% end %>
    </div>

  </tbody>
</table>
    
    <%= link_to 'Edit', edit_saleheader_path(@saleheader), class: "btn-primary btn-sm" %> | <%= link_to 'Back', saleheader_path,  class: "btn-primary btn-sm" %>
      <p>No hay detalles</p>
  


   
    
        
	       
			    