config/routes.rb
Rails.application.routes.draw do

  resources :saledetails
  
  resources :saleheaders do
    member do
      get 'show_saledetails' => 'saleheaders#show_saledetails'       
    end
  end
  
  resources :einvoices
  
  resources :products
  get 'graficos/index'

  resources :graficos
  resources :outkardexes
  resources :inkardexes 

  resources :compras do
    collection { post :import }
    collection { get :imprimir_datos }   
    collection { get :imprimir_codbarras }
  end

  resources :rotacion_inventarios

  resources :kardexes
  resources :conteos do
    collection { post :import }
  end
  resources :personas

  resources :regions

  resources :venta

  resources :equipos

  resources :fabricantes

  resources :visita

  resources :planvisita 

  resources :puntoventa

  resources :ciudads do
    collection { post :import }
  end

  resources :departamentos do
    collection { post :import }
  end

  resources :pais do
    collection { post :import }
  end

  resources :canals

  resources :tipocanals

  devise_for :users
  
  scope "/admin" do
    resources :users do
    collection { post :import }
    end    
  end
  
  resources :roles

  resources :users 

  resources :inventarios do
    collection { post :import }
    collection { get :imprimir_datos }   
    collection { get :imprimir_codbarras }
  end

  resources :tiendas
  

  resources :articulos do
    get 'reporte'  => 'articulos#reporte' 
    collection { post :import }  
    collection { get :rotacion_inventarios } 
    
    member do
      get 'show_inkardexes' => 'articulos#show_inkardexes'       
    end
  end

  resources :modelos 

  resources :componentes

  resources :medidas

  resources :empresas

  authenticated :user do
  end 
  root to: "welcome#index"
 

  end

app/models/tipocanal.rb
class Tipocanal < ActiveRecord::Base
  belongs_to :user
end

app/controllers/tipocanals_controller.rb
class TipocanalsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource


  # GET /tipocanals
  # GET /tipocanals.json
  def index
    @tipocanals = Tipocanal.all
  end

  # GET /tipocanals/1
  # GET /tipocanals/1.json
  def show
  end

  # GET /tipocanals/new
  def new

  end

  # GET /tipocanals/1/edit
  def edit
  end

  # POST /tipocanals
  # POST /tipocanals.json
  def create
    @tipocanal.user_id = current_user.id
    respond_to do |format|
      if @tipocanal.save
        format.html { redirect_to @tipocanal, notice: 'Tipocanal was successfully created.' }
        format.json { render :show, status: :created, location: @tipocanal }
      else
        format.html { render :new }
        format.json { render json: @tipocanal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipocanals/1
  # PATCH/PUT /tipocanals/1.json
  def update
    respond_to do |format|
      if @tipocanal.update(tipocanal_params)
        format.html { redirect_to @tipocanal, notice: 'Tipocanal was successfully updated.' }
        format.json { render :show, status: :ok, location: @tipocanal }
      else
        format.html { render :edit }
        format.json { render json: @tipocanal.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  # DELETE /tipocanals/1
  # DELETE /tipocanals/1.json
  def destroy
    @tipocanal.destroy
    respond_to do |format|
      format.html { redirect_to tipocanals_url, notice: 'Tipocanal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


    # Never trust parameters from the scary internet, only allow the white list through.
    def tipocanal_params
      params.require(:tipocanal).permit(:nombre, :user_id)
    end
end

app/helpers/tipocanals_helper.rb
module TipocanalsHelper
end

app/views/tipocanals/_form.html.erb
<%= form_for(@tipocanal) do |f| %>
  <% if @tipocanal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tipocanal.errors.count, "error") %> prohibited this tipocanal from being saved:</h2>

      <ul>
      <% @tipocanal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tipocanals/edit.html.erb
<h1>Editing Tipocanal</h1>

<%= render 'form' %>

<%= link_to 'Show', @tipocanal %> |
<%= link_to 'Back', tipocanals_path %>

app/views/tipocanals/index.html.erb
<h1>Listing Tipos Canal  <%= link_to '+', new_tipocanal_path %></h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tipocanals.each do |tipocanal| %>
      <tr>
        <td><%= tipocanal.nombre %></td>
        <td><%= tipocanal.user.name %></td>
        <td><%= link_to 'Show', tipocanal %></td>
        <td><%= link_to 'Edit', edit_tipocanal_path(tipocanal) %></td>
        <td><%= link_to 'Destroy', tipocanal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tipo Canal', new_tipocanal_path %>

app/views/tipocanals/new.html.erb
<h1>New Tipocanal</h1>

<%= render 'form' %>

<%= link_to 'Back', tipocanals_path %>

app/views/tipocanals/show.html.erb
<p>
  <strong>Nombre:</strong>
  <%= @tipocanal.nombre %>
</p>

<p>
  <strong>User:</strong>
  <%= @tipocanal.user.name %>
</p>

<%= link_to 'Edit', edit_tipocanal_path(@tipocanal) %> |
<%= link_to 'Back', tipocanals_path %>