config/routes.rb
Rails.application.routes.draw do

  resources :saledetails
  
  resources :saleheaders do
    member do
      get 'show_saledetails' => 'saleheaders#show_saledetails'       
    end
  end
  
  resources :einvoices
  
  resources :products
  get 'graficos/index'

  resources :graficos
  resources :outkardexes
  resources :inkardexes 

  resources :compras do
    collection { post :import }
    collection { get :imprimir_datos }   
    collection { get :imprimir_codbarras }
  end

  resources :rotacion_inventarios

  resources :kardexes
  resources :conteos do
    collection { post :import }
  end
  resources :personas

  resources :regions

  resources :venta

  resources :equipos

  resources :fabricantes

  resources :visita

  resources :planvisita 

  resources :puntoventa

  resources :ciudads do
    collection { post :import }
  end

  resources :departamentos do
    collection { post :import }
  end

  resources :pais do
    collection { post :import }
  end

  resources :canals

  resources :tipocanals

  devise_for :users
  
  scope "/admin" do
    resources :users do
    collection { post :import }
    end    
  end
  
  resources :roles

  resources :users 

  resources :inventarios do
    collection { post :import }
    collection { get :imprimir_datos }   
    collection { get :imprimir_codbarras }
  end

  resources :tiendas
  

  resources :articulos do
    get 'reporte'  => 'articulos#reporte' 
    collection { post :import }  
    collection { get :rotacion_inventarios } 
    
    member do
      get 'show_inkardexes' => 'articulos#show_inkardexes'       
    end
  end

  resources :modelos 

  resources :componentes

  resources :medidas

  resources :empresas

  authenticated :user do
  end 
  root to: "welcome#index"
 

  end

app/models/sale_detail.rb
class SaleDetail < ActiveRecord::Base
end

app/models/saledetail.rb
require 'rubygems'
require 'roo'

class Saledetail < ActiveRecord::Base
  belongs_to :user
  belongs_to :saleheader 
  belongs_to :articulo
  validates_presence_of :articulo_id, :line, :value, :quantity, :total
  
end

app/controllers/saledetails_controller.rb
class SaledetailsController < ApplicationController
  layout false , except: [:index, :new, :show, :edit ]
  before_action :set_saledetail, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  load_and_authorize_resource
  skip_authorize_resource

  # GET /saledetails
  # GET /saledetails.json
  def index
    @saledetails = Saledetail.all
  end

  # GET /saledetails/1
  # GET /saledetails/1.json
  def show
  end

  # GET /saledetails/new
  def new
    @saledetail = Saledetail.new
    compra = params[:value].to_f * params[:quantity].to_f
  end

  # GET /saledetails/1/edit
  def edit
  end
   def saleheader_inkardex
    @Saleheader = Saleheader.find(params[:id])
    @saledetail = Saledetail.new
  end

  # POST /saledetails
  # POST /saledetails.json
  def create
    @saledetail = Saledetail.new(saledetail_params)
    
    respond_to do |format|
      if @saledetail.save
        format.html { redirect_to @saledetail, notice: 'Saledetail was successfully created.' }
        format.json { render :show, status: :created, location: @saledetail }
      else
        format.html { render :new }
        format.json { render json: @saledetail.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /saledetails/1
  # PATCH/PUT /saledetails/1.json
  def update
    respond_to do |format|
      if @saledetail.update(saledetail_params)
        format.html { redirect_to @saledetail, notice: 'Saledetail was successfully updated.' }
        format.json { render :show, status: :ok, location: @saledetail }
      else
        format.html { render :edit }
        format.json { render json: @saledetail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /saledetails/1
  # DELETE /saledetails/1.json
  def destroy
    @saledetail.destroy
    respond_to do |format|
      format.html { redirect_to saledetails_url, notice: 'Saledetail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_saledetail
      @saledetail = Saledetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def saledetail_params
    
      params.require(:saledetail).permit(:articulo_id, :line, :quantity, :total, :discountpercent)
    end
end

app/helpers/saledetails_helper.rb
module SaledetailsHelper
end

app/views/saledetails/_form.html.erb
<%= form_for(@saledetail, remote: true, :html {:role => "form" }) do |f| %>

<script>
    $('input[type="text"]').on('blur', function() { 

        var Calc_total = $('#calculate_total');
        Calc_total;
        var total = value * quantity
        total;
    });
</script>

  <% if @saledetail.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@saledetail.errors.count, "error") %> prohibited this saledetail from being saved:</h2>

      <ul>
      <% @saledetail.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :Número_de_linea_en_la_factura%><br>
    <%= f.number_field :line%>
  </div>
  
   <div class="field">
    <%= f.label :Artículo%><br>
    <%= f.collection_select :articulo_id, Articulo.where(user_id: current_user.id).order(:nombre), :id, :name_with_desc, 
        include_blank: false %> 
  </div>

  <div class="field">
    <%= f.label :Valor_unitario_del_artículo %><br>
    <%= f.number_field :value  %>
  </div>
   <div class="field">
    <%= f.label :Cantidad_de_artículos_comprados %><br>
    <%= f.number_field :quantity%>
  </div>

  <div class="field">
    <%= f.label :total %><br>
    <%= f.number_field :total, class: "form-control", id: "calculate_total(:value, :quantity)" %>
  </div>

   <div class="field">
     <%= f.label :Ptje_Descuento %><br>
     <%= f.number_field :discountpercent, :class => 'text_field', :step => 0.1 %>
   </div>
     
   
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/saledetails/_saledetail.html.erb
<tbody>   
  <tr>
   <td><%= saledetail.articulo_id %></td>
   <td><%= saledetail.line %></td>
   <td><%= saledetail.value %></td>  
   <td><%= saledetail.discountpercent %></td>
   <td><%= saledetail.total %></td> 
   <td><%= link_to 'Show', saledetail, class: "btn btn-default btn-sm" %></td>
   <td><%= link_to 'Edit', edit_saledetail_path(saledetail), class: "btn btn-default btn-sm" %></td>
   <td><%= button_to 'Delete',saledetail, class: "btn btn-danger btn-sm", method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>  
</tbody>

app/views/saledetails/edit.html.erb
<h1>Editing Saledetail</h1>

<%= render 'form' %>

<%= link_to 'Show', @saledetail %> |
<%= link_to 'Back', saledetails_path %>

app/views/saledetails/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Saledetails</h1>
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>line</th>
      <th>articulo_id</th>      
      <th>value</th>
      <th>quantity</th>
      <th>total </th>
      <th>discountpercent</th>
       
      <th colspan="3"></th>
     </tr>
  </thead>


  <tbody>
    <% @saledetails.each do |saledetail| %>
     <td><%= saledetail.line %></td>
     <td><%= saledetail.articulo_id %></td>     
     <td><%= saledetail.value %></td>
     <td><%= saledetail.quantity %></td>
     <td><%= saledetail.total%></td>
     <td><%= saledetail.discountpercent %></td>
      <tr>
        
        <td><%= link_to 'Show', saledetail %></td>
        <td><%= link_to 'Edit', edit_saledetail_path(saledetail) %></td>
        <% if can? :destroy, saledetail %>
          <td><%= link_to 'Destroy', saledetail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New Saledetail', new_saledetail_path %>

app/views/saledetails/new.html.erb
<h1>New Saledetail</h1>

<%= render 'form' %>

<%= link_to 'Back', saledetails_path %>

app/views/saledetails/saleheader_saledetail.html.erb
<h1>New saledetail</h1>
<%= render 'form' %>
<%= link_to 'Back', show_saledetails_saleheader_path, class: "btn btn-default btn-sm" %>

app/views/saledetails/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Número_de_linea_en_la_factura:</strong>
  <%= @saledetail.line %>
</p>

<p>
  <strong>Articulo:</strong>
  <%= @saledetail.articulo_id%>
</p>

<p>
  <strong>value :</strong>
  <%= @saledetail.value  %>

</p>

<p>
  <strong>total:</strong>
  <%= @saledetail.total %>
</p>

<p>
  <strong>discountpercent:</strong>
  <%= @saledetail.discountpercent%>
  </p>


<%= link_to 'Edit', edit_saledetail_path(@saledetail) %> |
<%= link_to 'Back', saledetails_path %>

app/views/saledetails/update.js.erb
$('#dialog').modal('toggle');
$('#saledetail_<%= @saledetail.id %>').replaceWith('<%= j render (@saledetail) %>')