config/routes.rb
Rails.application.routes.draw do

  resources :saledetails
  
  resources :saleheaders do
    member do
      get 'show_saledetails' => 'saleheaders#show_saledetails'       
    end
  end
  
  resources :einvoices
  
  resources :products
  get 'graficos/index'

  resources :graficos
  resources :outkardexes
  resources :inkardexes 

  resources :compras do
    collection { post :import }
    collection { get :imprimir_datos }   
    collection { get :imprimir_codbarras }
  end

  resources :rotacion_inventarios

  resources :kardexes
  resources :conteos do
    collection { post :import }
  end
  resources :personas

  resources :regions

  resources :venta

  resources :equipos

  resources :fabricantes

  resources :visita

  resources :planvisita 

  resources :puntoventa

  resources :ciudads do
    collection { post :import }
  end

  resources :departamentos do
    collection { post :import }
  end

  resources :pais do
    collection { post :import }
  end

  resources :canals

  resources :tipocanals

  devise_for :users
  
  scope "/admin" do
    resources :users do
    collection { post :import }
    end    
  end
  
  resources :roles

  resources :users 

  resources :inventarios do
    collection { post :import }
    collection { get :imprimir_datos }   
    collection { get :imprimir_codbarras }
  end

  resources :tiendas
  

  resources :articulos do
    get 'reporte'  => 'articulos#reporte' 
    collection { post :import }  
    collection { get :rotacion_inventarios } 
    
    member do
      get 'show_inkardexes' => 'articulos#show_inkardexes'       
    end
  end

  resources :modelos 

  resources :componentes

  resources :medidas

  resources :empresas

  authenticated :user do
  end 
  root to: "welcome#index"
 

  end

app/models/canal.rb
class Canal < ActiveRecord::Base
  belongs_to :tipocanal
  belongs_to :user

  def tipocanal_nombre=(nombre)
  	tipocanal.try(:nombre)
  end
end

app/controllers/canals_controller.rb
class CanalsController < ApplicationController
  before_action :authenticate_user!
  load_and_authorize_resource


  # GET /canals
  # GET /canals.json
  def index
    @canals = Canal.all
  end

  # GET /canals/1
  # GET /canals/1.json
  def show
  end

  # GET /canals/new
  def new

  end

  # GET /canals/1/edit
  def edit
  end

  # POST /canals
  # POST /canals.json
  def create

    @canal.user_id = current_user.id
    respond_to do |format|
      if @canal.save
        format.html { redirect_to @canal, notice: 'Canal was successfully created.' }
        format.json { render :show, status: :created, location: @canal }
      else
        format.html { render :new }
        format.json { render json: @canal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /canals/1
  # PATCH/PUT /canals/1.json
  def update
    respond_to do |format|
      if @canal.update(canal_params)
        format.html { redirect_to @canal, notice: 'Canal was successfully updated.' }
        format.json { render :show, status: :ok, location: @canal }
      else
        format.html { render :edit }
        format.json { render json: @canal.errors, status: :unprocessable_entity }
      end
    end
  end


  private

  # DELETE /canals/1
  # DELETE /canals/1.json
  def destroy
    @canal.destroy
    respond_to do |format|
      format.html { redirect_to canals_url, notice: 'Canal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

    # Never trust parameters from the scary internet, only allow the white list through.
    def canal_params
      params.require(:canal).permit(:name, :tipocanal_id, :user_id)
    end
end

app/helpers/canals_helper.rb
module CanalsHelper
end

app/views/canals/_form.html.erb
<%= form_for(@canal) do |f| %>
  <% if @canal.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@canal.errors.count, "error") %> prohibited this canal from being saved:</h2>

      <ul>
      <% @canal.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :tipocanal_id %><br>
    <%= f.collection_select :tipocanal_id, Tipocanal.order(:nombre), :id, :nombre, include_blank: true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/canals/edit.html.erb
<h1>Editing Canal</h1>

<%= render 'form' %>

<%= link_to 'Show', @canal %> |
<%= link_to 'Back', canals_path %>

app/views/canals/index.html.erb
<h1>Listing Canales  <%= link_to '+', new_canal_path %></h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Tipocanal</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @canals.each do |canal| %>
      <tr>
        <td><%= canal.name %></td>     
        <td><%= canal.tipocanal.nombre %></td>
        <td><%= canal.user.name %></td>
        <td><%= link_to 'Show', canal %></td>
        <td><%= link_to 'Edit', edit_canal_path(canal) %></td>
        <td><%= link_to 'Destroy', canal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Canal', new_canal_path %>

app/views/canals/new.html.erb
<h1>New Canal</h1>

<%= render 'form' %>

<%= link_to 'Back', canals_path %>

app/views/canals/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @canal.name %>
</p>

<p>
  <strong>Tipocanal:</strong>
  <%= @canal.tipocanal.nombre %>
</p>

<p>
  <strong>User:</strong>
  <%= @canal.user.name %>
</p>

<%= link_to 'Edit', edit_canal_path(@canal) %> |
<%= link_to 'Back', canals_path %>